# dump-and-encrypt-secrets.yml
#
# This manually run workflow takes an age public key as input, puts all of a
# GitHub repo's secrets into env vars, dumps all env vars, encrypts them with
# age, and creates an artifact that you can download and decrypt with your age
# private key.
#
# To use this workflow:
#
# 1. Put this file in the `.github/workflows/` folder, commit, and push.
# 2. Install age. See https://github.com/FiloSottile/age
# 3. Run `age-keygen > /tmp/key.txt` to generate a key.
# 4. Click "Actions" in your GitHub repo.
# 5. Find this workflow on the left, select it, and click Run Workflow.
# 6. Enter your age public key.
# 7. Download the file from "Artifact download URL" at the bottom.
# 8. Decrypt it with: `unzip -p ~/Downloads/env.age.zip env.age | age -d -i /tmp/key.txt`

on:
  workflow_dispatch:
    inputs:
      age_key:
        description: 'Enter a public age key'
        required: true
        type: string
jobs:
  dump-and-encrypt-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Install age
        run: |
          sudo apt-get update
          sudo apt-get install -y age
      - env: ${{ secrets }}
        run: |
          env | age -a -e -r "${{ inputs.age_key }}" > env.age
      - uses: actions/upload-artifact@v4.6.1
        with:
          name: env.age
          path: env.age
          retention-days: 1
